# Generated by Django 4.2.11 on 2024-11-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='capacity',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='base.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
